### ISSUE TITLE
Running the program

### ISSUE THREAD

**Issue by Sattishh** [mohammed28ali/Fiction-AR#1]
Hello, I was wondering how I could run this program?

**Comment by mohammed28ali** [comment]
clone in android studio or download zip file and extract then open by android studio

**Comment by Sattishh** [comment]
Ah I see, also a side question I had is, how can I add 2D image by using arCodeController, arCodeMaterial, etc.

**Comment by mohammed28ali** [comment]
you can use unity or search about glb 3dimages and add it to assets

**Comment by Sattishh** [comment]
Got it, thank you so much for your help! @mohammed28ali
